---
# tasks file to install oh my zsh

- name: Check if Oh My Zsh is already installed
  ansible.builtin.shell: echo $ZSH
  register: isOmz

- name: Install Oh My Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: IsOmz.rc != 0
